# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lean Mapper
email: miras.paulik@seznam.cz
description: > # this means to ignore newlines until "baseurl:"
   Lean Mapper is a tiny ORM based on powerful dibi database abstraction library for PHP 5.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: MiraPaulik
github_username:  castamir

# Build settings
exclude: ['tests']
markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

gems:
  - jekyll-redirect-from
